# Generated by Django 3.2.16 on 2024-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todos_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
