# Generated by Django 3.2.16 on 2024-09-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todos_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='priority',
        ),
    ]
