# Generated by Django 3.2.16 on 2024-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_remove_todos_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
