# Generated by Django 3.2.16 on 2024-09-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_todos_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='finished',
            new_name='is_finished',
        ),
    ]
