# Generated by Django 3.2.16 on 2024-09-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_rename_finished_todos_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='is_finished',
            new_name='finished',
        ),
    ]
