# Generated by Django 3.2.16 on 2024-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_rename_is_finished_todos_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
