# Generated by Django 3.2.16 on 2024-09-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_todos_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
