# Generated by Django 3.2.16 on 2024-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_todos_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
