# Generated by Django 3.2.16 on 2024-10-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_todos_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='todo_app.todos')),
            ],
        ),
    ]
