# Generated by Django 3.2.16 on 2024-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_auto_20241004_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='files',
            field=models.ManyToManyField(blank=True, to='todo_app.UploadedFile'),
        ),
    ]
